version: '2'
services:
  merger:
    build:
      context: ../..
      dockerfile: docker/Dockerfile
    network_mode: host
    image: mavros:merger
    volumes:
      - ./logs:/root/.ros/log:rw
      - .:/root/catkin_ws/src/mavros_merger
    command: roslaunch mavros_merger main.launch
    env_file:
      - ros.env
  mavproxy:
    build: ../mavproxy
    network_mode: host
    image: mavproxy
    command: mavproxy.py --master=:14550 --out=:14551 --out=:192.168.201.59:14550
